name: CloudFormation Guard Validate

on:
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions: write-all
    name: CloudFormation Guard validate
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './rules'
          data: './data'
          create-review: false